### ISSUE TITLE
Restarting iPad requires Re-jailbreaking

### ISSUE THREAD

**Issue by emeraldongithub** [pwned4ever/Th0r_Freya#11]
m

**Comment by pwned4ever** [comment]
That's normal for every jailbreak since iOS 10

Sent from my iPhone

On Nov 3, 2022, at 1:29 AM, emeraldyy ***@***.***> wrote:

﻿

m

**Comment by Skridiotic** [comment]
thats how semi-untethered jailbreaks work

**Comment by pwned4ever** [comment]
I Believe this has been resolved. If any further arises please reopen a new issue
