### ISSUE TITLE
Can't install IPA file with filza

### ISSUE THREAD

**Issue by DangDev** [pwned4ever/Th0r_Freya#12]

**Comment by pwned4ever** [comment]
Shouldn't ever be installed with filza

Sent from my iPhone

On Nov 9, 2022, at 12:10 PM, DangDev ***@***.***> wrote:

﻿

**Comment by emeraldongithub** [comment]
> _No description provided._

install the tweak "appsync unified" on the repo "cydia.akemi.ai"
https://cydia.akemi.ai/?page/ai.akemi.appsyncunified

**Comment by pwned4ever** [comment]
I Believe this has been resolved. If any further arises please reopen a new issue
