### ISSUE TITLE
System reboot when jailbreaking

### ISSUE THREAD

**Issue by Alex222222222222** [pwned4ever/Th0r_Freya#13]
The system reboot when jailbreaking, this always happen after the message
```
[+] ikm_size: 32680
```

On iPhone 5s global, IOS 12.5.6

As the system reboot, I cannot see any logs relate to this.

**Comment by pwned4ever** [comment]
How many attempts have you tried qfter a restart of the device? Either wait a minute before using the jailbreak after the device boots up. Or just constantly try the jailbreak until it works. It's has never in my history failed 10x in a row so. With that said. Keep trying until a further error appears.

Sent from my iPhone

On Nov 19, 2022, at 3:09 AM, Zifan Hua ***@***.***> wrote:

﻿

The system reboot when jailbreaking, this always happen after the message

[+] ikm_size: 32680


On iPhone 5s global, IOS 12.5.6

As the system reboot, I cannot see any logs relate to this.

**Comment by Alex222222222222** [comment]
I figured out, that was because of a lack of ram on my device.

If I run some heavy task in the background, and start jailbreak, my device reboots.

**Comment by pwned4ever** [comment]
That's great you solved it. Maybe one day I can add a prompt to the load up that mentions to close all running apps before initializing the Jailbreak

**Comment by Alex222222222222** [comment]
Do you consider writing a short guide for using Freya in the README? Ans also put all common issues and important notices there.

I successfully jailbreak my device. But still, have some problems with Freya. For instance, I am still quite not sure whether the FixFS option will delete all my installed tweaks or not. 

Also, some issue for #9 , I tried install substitute, but that breaks the `Cydia Substrate Dummy` and spring board boot into safe mode.

Thanks in advance.
