### ISSUE TITLE
freya is the very ipa which is the only jailbreak tools can jailbreak ios12.5.6

### ISSUE THREAD

**Issue by villager1314** [pwned4ever/Th0r_Freya#19]
but i wish song can come back.
When I switch the app from home to settings, his icon suddenly becomes larger.

https://user-images.githubusercontent.com/92611156/211810759-3c79ae94-640b-40b1-bb1f-2f290600f7bb.MOV

**Comment by villager1314** [comment]
iPhone 5s,in addition,I found that when I has jailbroken my device,it shows “jailbreak” or “enable freya”

**Comment by pwned4ever** [comment]
I Believe this has been resolved. If any further arises please reopen a new issue
