### ISSUE TITLE
Jbd Error after restore rootfs

### ISSUE THREAD

**Issue by benjamin920101** [pwned4ever/Th0r_Freya#24]
![C2F145B5-A05B-4D38-A8E8-63251A276910](https://user-images.githubusercontent.com/47590892/213428832-6cabdaa0-156b-449c-a023-ee4cadad3e20.png)

**Comment by villager1314** [comment]
You can reboot your device  once or twice by yourself rather than press “ okay “

**Comment by villager1314** [comment]
If It can't work properly, try to ask the author.

**Comment by pwned4ever** [comment]
next update should fix this issue

**Comment by benjamin920101** [comment]
Thank you very much
