### ISSUE TITLE
(Error feedback) When you download Cr4shed and restart device, it will prevent Cydia from loading data and loading the package list.

### ISSUE THREAD

**Issue by villager1314** [pwned4ever/Th0r_Freya#32]
After uninstalling Cr4shed with Sileo, Cydia returned to normal operation.

**Comment by villager1314** [comment]
Crashreporter doesn't work because it gives the cause of the accident that does not match the application and dependency I downloaded.

**Comment by pwned4ever** [comment]
Do you have Twitter?

Sent from my iPhone

On Feb 4, 2023, at 1:20 AM, villager1314 ***@***.***> wrote:

﻿

Crashreporter doesn't work because it gives the cause of the accident that does not match the application and dependency I downloaded.

**Comment by villager1314** [comment]
no😭😭🙈🙈

**Comment by villager1314** [comment]
Is your Twitter account pwned4⃣️ever?

**Comment by villager1314** [comment]
If so, I will pay attention to the latest developments.

**Comment by pwned4ever** [comment]
issued resolved in 1.3.6 afaik
