### ISSUE TITLE
/bin/sh: Permission denied

### ISSUE THREAD

**Issue by Eurothopia** [pwned4ever/Th0r_Freya#33]
Shell somehow doesn’t work so neither tweaks work

![4CCFDE7A-5E99-494A-8F85-1CBFD7024C5C](https://user-images.githubusercontent.com/90931142/217026120-cc5f1b10-25c6-4c5d-ab33-71740de3d9f1.jpeg)

```
[+] execCmdV(216): Calling dlopen...
[+] execCmdV(216): dlopen returned 0x08070000
[+] execCmdV(216): No error occurred!
[+] execCmdV(216): Injection succeeded!
[+] execCmdV(216) completed with exit status 0
[+] amfid has been infected by our dynamic library, it is now dismantled
[+] Amfid bombed without bootstrapping!
[+] execCmdV(217) command: /freya/launchctl "load" "/freya/LD/suckmyd.plist"
[+] execCmdV(217) completed with exit status 0
[+] jbd has been loaded!
[+] Patching XPCPROXY...
[+] /usr/libexec/xpcproxy.sliced Does Not Exist! Continuing...
[+] Patched Executable!
[+] execCmdV(219) command: /freya/jtool "--sign" "--inplace" "--ent" "/freya/default.ent" "/usr/libexec/xpcproxy.sliced"
[+] execCmdV(219) completed with exit status 0
[+] Hello?
[+] execCmdV(221) command: /bin/sh "-c" "echo 'really jailbroken';shopt -s nullglob;for a in /Library/LaunchDaemons/*.plist;do echo loading $a;launchctl load "$a" ;done; "
[-] execCmdV(221): ERROR posix_spawn failed (13): Permission denied
[+] execCmdV(222) command: /bin/sh "-c" "for file in /etc/rc.d/*; do if [[ -x "$file" && "$file" != "/etc/rc.d/substrate" ]]; then "$file";fi;done"
[-] execCmdV(222): ERROR posix_spawn failed (13): Permission denied
```
on iPhone 6 12.5.6

**Comment by pwned4ever** [comment]
What version of freya are you using? Remove your jailbreak and start over with 1.3.6

Sent from my iPhone

On Feb 6, 2023, at 11:21 AM, Eurothopia ***@***.***> wrote:

﻿

Shell somehow doesn’t work so neither tweaks work

[4CCFDE7A-5E99-494A-8F85-1CBFD7024C5C]<https://user-images.githubusercontent.com/90931142/217026120-cc5f1b10-25c6-4c5d-ab33-71740de3d9f1.jpeg>

[+] execCmdV(216): Calling dlopen...
[+] execCmdV(216): dlopen returned 0x08070000
[+] execCmdV(216): No error occurred!
[+] execCmdV(216): Injection succeeded!
[+] execCmdV(216) completed with exit status 0
[+] amfid has been infected by our dynamic library, it is now dismantled
[+] Amfid bombed without bootstrapping!
[+] execCmdV(217) command: /freya/launchctl "load" "/freya/LD/suckmyd.plist"
[+] execCmdV(217) completed with exit status 0
[+] jbd has been loaded!
[+] Patching XPCPROXY...
[+] /usr/libexec/xpcproxy.sliced Does Not Exist! Continuing...
[+] Patched Executable!
[+] execCmdV(219) command: /freya/jtool "--sign" "--inplace" "--ent" "/freya/default.ent" "/usr/libexec/xpcproxy.sliced"
[+] execCmdV(219) completed with exit status 0
[+] Hello?
[+] execCmdV(221) command: /bin/sh "-c" "echo 'really jailbroken';shopt -s nullglob;for a in /Library/LaunchDaemons/*.plist;do echo loading $a;launchctl load "$a" ;done; "
[-] execCmdV(221): ERROR posix_spawn failed (13): Permission denied
[+] execCmdV(222) command: /bin/sh "-c" "for file in /etc/rc.d/*; do if [[ -x "$file" && "$file" != "/etc/rc.d/substrate" ]]; then "$file";fi;done"
[-] execCmdV(222): ERROR posix_spawn failed (13): Permission denied

**Comment by Eurothopia** [comment]
First upgraded from 1.2.7 to 1.3.3, it started complaining about unable to create a symlink in /Library/MobileSubstrate/DynamicLibraries (File exists). Then reinstalled cydia and upgraded to 1.3.6 and 1.3.7, still happening

**Comment by pwned4ever** [comment]
Don't just upgrade and enable the jailbreak. Like I said, get 1.3.6. Remove your jailbreak and start fresh with 1.3.6

Sent from my iPhone

On Feb 6, 2023, at 1:43 PM, Eurothopia ***@***.***> wrote:

﻿

First upgraded from 1.2.7 to 1.3.3, it started complaining about unable to create a symlink in /Library/MobileSubstrate/DynamicLibraries (File exists). Then reinstalled cydia and upgraded to 1.3.6 and 1.3.7, still happening

**Comment by Eurothopia** [comment]
Okay thanks I'll try later

**Comment by pwned4ever** [comment]
Let me know

Sent from my iPhone

On Feb 6, 2023, at 1:45 PM, Eurothopia ***@***.***> wrote:

﻿

Okay thanks I'll try later

**Comment by Eurothopia** [comment]
Yup, works normally now, tysm for freya

**Comment by pwned4ever** [comment]
💙thank you for such kindness

Sent from my iPhone

On Feb 8, 2023, at 11:32 AM, Eurothopia ***@***.***> wrote:

﻿

Yup, works normally now, tysm for freya
