### ISSUE TITLE
iOS 12.5.7 support

### ISSUE THREAD

**Issue by emeraldongithub** [pwned4ever/Th0r_Freya#34]
I am still on 12.5.6, but i am worried on what the future holds. 12.5.7 exists now and 12.5.6 is now dead, unsigned. This is an issue, Please add 12.5.7 support.

**Comment by pwned4ever** [comment]
support is already added for iOS 12.5.7, enjoy...

**Comment by pwned4ever** [comment]
12.5.7 removes the health of your battery percentage, whatever your preference is, to stay on 12.5.6 or upgrade to 12.5.7
