### ISSUE TITLE
How to remove jailbreak ? remove cydia and all without restoring iphone using itunes

### ISSUE THREAD

**Issue by DEAD404ERROR** [pwned4ever/Th0r_Freya#38]

**Comment by pwned4ever** [comment]
Click settings at the bottom of the app, only when you're not in a jailbreak mode and the turn on restore rootfs, click home at the bottom to go back to jailbreak start page.
Click remove freya button after turning in restorerootfs switch.
Sent from my iPhone

On Apr 13, 2023, at 12:20 PM, DEAD404ERROR ***@***.***> wrote:

﻿

**Comment by DEAD404ERROR** [comment]
thanks tht works
