### ISSUE TITLE
There is source code?

### ISSUE THREAD

**Issue by platinumstufff** [pwned4ever/Th0r_Freya#41]

**Comment by pwned4ever** [comment]
Used to be. If someone forked it maybe youCan grab it from them. I've close sourced it now. As R/jailbreak doesn't deserve it to be opened sourced as they don't mention it as a real jailbreak to the rest of the jailbreak community. Just got fed up with so called copy paste of code that isn't even available, saying I didn't create this jailbreak. 🤣

Sent from my iPhone

On May 13, 2023, at 6:22 PM, platinumstufff ***@***.***> wrote:

﻿

**Comment by platinumstufff** [comment]
Thank you for the asnwer.
