### ISSUE TITLE
Cant jail iphone 5s 12.5.7

### ISSUE THREAD

**Issue by adv-zl** [pwned4ever/Th0r_Freya#53]
![image](https://github.com/pwned4ever/Th0r_Freya/assets/16443377/7855f1d1-3dff-4ca9-bf46-b50d94d656f5)

Failed to leak ipc_kmsg error

Why it happens?

**Comment by pwned4ever** [comment]
You're trying to fast possibly. Wait a couple of more seconds before trying it

Sent from my iPhone

On Nov 9, 2023, at 2:46 PM, AE ***@***.***> wrote:

﻿

Closed #53<https://github.com/pwned4ever/Th0r_Freya/issues/53> as completed.
