### ISSUE TITLE
Sileo does not open

### ISSUE THREAD

**Issue by JoshAtticus** [pwned4ever/Th0r_Freya#54]
Title

Even in safe mode, Sileo refuses to open, only Cydia. Very annoying because Sileo is 1000000X better than Cydia

Using iPhone 5s iOS 12.5.7 (accidentally updated from iOS 9.2 🙃)

**Comment by JoshAtticus** [comment]
doesn't matter anymore because I broke my iPhone 5s and I hate myself for it

**Comment by pwned4ever** [comment]
Fml 🤦🏻‍♂️

Sent from my iPhone

On Nov 18, 2023, at 6:13 AM, Josh ***@***.***> wrote:

﻿

doesn't matter anymore because I broke my iPhone 5s and I hate myself for it
