### ISSUE TITLE
No Cydia app

### ISSUE THREAD

**Issue by Seraldi** [pwned4ever/Th0r_Freya#6]
Hi, I’m doing it on an iPad Air, I’m able to jailbreak successfully but there’s technically no Cydia or terminal app. There’s no icons nor do they show up when searched for however Cydia does open when redirected to via browser.

**Comment by pwned4ever** [comment]
I've figured out the problem, however I'm currently not sure how to fix it as it should've done what it does for other devices and worked but for iPads I'm having an issue modifying the springboard.plist file. I'm currently working on finding a fix to solve this major bug issue

Sent from my iPhone

On Oct 13, 2022, at 12:10 PM, Seraldi ***@***.***> wrote:

﻿

Hi, I’m doing it on an iPad Air, I’m able to jailbreak successfully but there’s technically no Cydia or terminal app. There’s no icons nor do they show up when searched for however Cydia does open when redirected to via browser.
