### ISSUE TITLE
Ipod 5th gen failed snapshot 

### ISSUE THREAD

**Issue by EPiCxRIOTZZ** [pwned4ever/Th0r_Freya#7]

**Comment by pwned4ever** [comment]
What version of ios are you on? Check your settings - general - iPhone storage, for the system update file. If it's there, remove/delete, reboot, turn off wifi so it doesn't redownload while jailbreaking.

Sent from my iPhone

On Oct 17, 2022, at 9:28 AM, _IBTDEV_ ***@***.***> wrote:

﻿
